- name: Copy Nginx configuration file for WordPress
  copy:
    src: ../nginx_wordpress.conf
    dest: /etc/nginx/sites-available/wordpress
    mode: '0644'

- name: Enable Nginx configuration for WordPress
  file:
    src: /etc/nginx/sites-available/wordpress
    dest: /etc/nginx/sites-enabled/wordpress
    state: link
