services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      HTTP_HOST: ${HTTP_HOST}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WORDPRESS_EMAIL}
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - /home/ubuntu/docker/wordpress/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    restart: always
    networks:
      - wordpress_network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network:
    driver: bridge
