- hosts: webserver
  become: yes
  tasks:
  
    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes

    - name: Installer les dépendances nécessaires
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker APT
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Mettre à jour l'index des paquets APT
      apt:
        update_cache: yes

    - name: Installer Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Installer le plugin Docker Compose
      apt:
        name: docker-compose-plugin
        state: present

    - name: Démarrer et activer le service Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Créer le répertoire pour Docker Compose
      file:
        path: /home/{{ ansible_user }}/cloud_1
        state: directory
        mode: '0755'

    - name: Copier docker-compose.yml sur le serveur
      copy:
        src: ./docker-compose.yml
        dest: /home/{{ ansible_user }}/cloud_1/docker-compose.yml
        mode: '0644'

    - name: Copier db.env sur le serveur
      copy:
        src: ./db.env
        dest: /home/{{ ansible_user }}/cloud_1/db.env
        mode: '0600'

    - name: Lancer Docker Compose pour déployer les services
      command: docker compose up -d
      args:
        chdir: /home/{{ ansible_user }}/cloud_1
